const series = [
  {
    name: "ac diam cras pellentesque",
    color: "#dbd0b6",
    serializedTo: 20,
    subsetId: 1,
  },
  { name: "amet diam in", color: "#3babfd", serializedTo: null, subsetId: 1 },
  {
    name: "tincidunt eu felis",
    color: "#5c9446",
    serializedTo: null,
    subsetId: 1,
  },
  { name: "sit amet", color: "#e2a2b6", serializedTo: null, subsetId: 1 },
  {
    name: "cum sociis natoque",
    color: "#682e5e",
    serializedTo: 30,
    subsetId: 1,
  },
  {
    name: "ipsum integer a nibh",
    color: "#5b0fdc",
    serializedTo: null,
    subsetId: 2,
  },
  {
    name: "amet nunc viverra dapibus",
    color: "#89b68d",
    serializedTo: null,
    subsetId: 2,
  },
  {
    name: "nulla mollis molestie lorem",
    color: "#ebecae",
    serializedTo: null,
    subsetId: 2,
  },
  {
    name: "molestie nibh in lectus pellentesque",
    color: "#505a71",
    serializedTo: null,
    subsetId: 2,
  },
  {
    name: "ac nibh fusce lacus purus",
    color: "#58e01c",
    serializedTo: null,
    subsetId: 2,
  },
  {
    name: "vulputate nonummy maecenas",
    color: "#d4b0fa",
    serializedTo: 220,
    subsetId: 3,
  },
  {
    name: "ante vel ipsum praesent",
    color: "#fc902f",
    serializedTo: 100,
    subsetId: 3,
  },
  {
    name: "augue luctus tincidunt nulla mollis",
    color: "#369694",
    serializedTo: null,
    subsetId: 3,
  },
  {
    name: "cubilia curae donec",
    color: "#277618",
    serializedTo: 200,
    subsetId: 3,
  },
  {
    name: "duis consequat dui nec",
    color: "#a75e70",
    serializedTo: null,
    subsetId: 3,
  },
  {
    name: "dignissim vestibulum vestibulum ante",
    color: "#8980ad",
    serializedTo: null,
    subsetId: 4,
  },
  {
    name: "suspendisse accumsan tortor quis turpis",
    color: "#a931da",
    serializedTo: null,
    subsetId: 4,
  },
  {
    name: "eu interdum eu tincidunt",
    color: "#3b9dac",
    serializedTo: null,
    subsetId: 4,
  },
  {
    name: "ridiculus mus etiam",
    color: "#bddfa5",
    serializedTo: null,
    subsetId: 4,
  },
  {
    name: "mauris laoreet ut rhoncus aliquet",
    color: "#b569dd",
    serializedTo: null,
    subsetId: 4,
  },
  {
    name: "sit amet cursus id turpis",
    color: "#2c8150",
    serializedTo: null,
    subsetId: 5,
  },
  {
    name: "elit proin risus praesent lectus",
    color: "#6d77a8",
    serializedTo: 150,
    subsetId: 5,
  },
  { name: "faucibus orci", color: "#5f6f81", serializedTo: null, subsetId: 5 },
  {
    name: "eu nibh quisque",
    color: "#42dfaf",
    serializedTo: null,
    subsetId: 5,
  },
  { name: "tempus sit", color: "#79fb76", serializedTo: null, subsetId: 5 },
  {
    name: "id pretium iaculis diam",
    color: "#52650d",
    serializedTo: null,
    subsetId: 6,
  },
  { name: "cum sociis", color: "#6ef012", serializedTo: null, subsetId: 6 },
  { name: "ut at dolor", color: "#811f84", serializedTo: 240, subsetId: 6 },
  {
    name: "maecenas rhoncus",
    color: "#ffb13e",
    serializedTo: null,
    subsetId: 6,
  },
  {
    name: "magna vulputate luctus cum sociis",
    color: "#14139d",
    serializedTo: null,
    subsetId: 6,
  },
  {
    name: "nisl venenatis lacinia",
    color: "#568a80",
    serializedTo: null,
    subsetId: 7,
  },
  { name: "mattis nibh", color: "#a61ee5", serializedTo: null, subsetId: 7 },
  {
    name: "viverra dapibus nulla suscipit ligula",
    color: "#46446d",
    serializedTo: null,
    subsetId: 7,
  },
  {
    name: "volutpat eleifend donec ut dolor",
    color: "#a08359",
    serializedTo: null,
    subsetId: 7,
  },
  {
    name: "maecenas rhoncus aliquam lacus",
    color: "#06471c",
    serializedTo: null,
    subsetId: 7,
  },
  {
    name: "curabitur gravida",
    color: "#0d924b",
    serializedTo: null,
    subsetId: 8,
  },
  {
    name: "nam nulla integer pede",
    color: "#a85180",
    serializedTo: null,
    subsetId: 8,
  },
  {
    name: "erat vestibulum sed magna",
    color: "#c781f0",
    serializedTo: null,
    subsetId: 8,
  },
  {
    name: "pellentesque eget nunc",
    color: "#0c6853",
    serializedTo: null,
    subsetId: 8,
  },
  {
    name: "lectus aliquam sit amet diam",
    color: "#ee6dbf",
    serializedTo: null,
    subsetId: 8,
  },
  { name: "sapien ut", color: "#96b9d9", serializedTo: null, subsetId: 9 },
  { name: "molestie nibh in", color: "#de44bf", serializedTo: 30, subsetId: 9 },
  {
    name: "phasellus id sapien in sapien",
    color: "#2a57df",
    serializedTo: null,
    subsetId: 9,
  },
  {
    name: "nisi vulputate nonummy",
    color: "#4638b3",
    serializedTo: null,
    subsetId: 9,
  },
  {
    name: "quisque arcu libero",
    color: "#1b39d2",
    serializedTo: null,
    subsetId: 9,
  },
  {
    name: "vestibulum vestibulum ante",
    color: "#bfd946",
    serializedTo: null,
    subsetId: 10,
  },
  {
    name: "maecenas leo odio condimentum",
    color: "#cfc950",
    serializedTo: null,
    subsetId: 10,
  },
  { name: "duis ac", color: "#edf8c1", serializedTo: null, subsetId: 10 },
  {
    name: "aliquam erat volutpat in",
    color: "#ab471e",
    serializedTo: null,
    subsetId: 10,
  },
  {
    name: "lectus aliquam",
    color: "#017065",
    serializedTo: null,
    subsetId: 10,
  },
  {
    name: "pellentesque at",
    color: "#08e8ec",
    serializedTo: null,
    subsetId: 11,
  },
  {
    name: "duis faucibus accumsan odio curabitur",
    color: "#bfd941",
    serializedTo: null,
    subsetId: 11,
  },
  {
    name: "est lacinia nisi venenatis",
    color: "#074ef2",
    serializedTo: null,
    subsetId: 11,
  },
  {
    name: "ut tellus nulla ut",
    color: "#8a5c1d",
    serializedTo: 140,
    subsetId: 11,
  },
  {
    name: "at nunc commodo placerat",
    color: "#3af3cd",
    serializedTo: null,
    subsetId: 11,
  },
  {
    name: "tincidunt ante vel ipsum praesent",
    color: "#e0fbd4",
    serializedTo: null,
    subsetId: 12,
  },
  {
    name: "augue luctus tincidunt nulla mollis",
    color: "#61037a",
    serializedTo: null,
    subsetId: 12,
  },
  {
    name: "purus eu magna vulputate luctus",
    color: "#312d83",
    serializedTo: null,
    subsetId: 12,
  },
  {
    name: "magnis dis parturient montes nascetur",
    color: "#965cd7",
    serializedTo: null,
    subsetId: 12,
  },
  {
    name: "felis sed lacus morbi sem",
    color: "#f7a38c",
    serializedTo: 130,
    subsetId: 12,
  },
  { name: "ac tellus", color: "#2b6b6b", serializedTo: null, subsetId: 13 },
  {
    name: "semper rutrum nulla nunc purus",
    color: "#1fde71",
    serializedTo: 40,
    subsetId: 13,
  },
  {
    name: "arcu sed augue aliquam",
    color: "#c56f53",
    serializedTo: 60,
    subsetId: 13,
  },
  {
    name: "erat quisque erat",
    color: "#c44842",
    serializedTo: null,
    subsetId: 13,
  },
  { name: "molestie sed", color: "#116fe4", serializedTo: null, subsetId: 13 },
  { name: "justo in", color: "#28906b", serializedTo: null, subsetId: 14 },
  {
    name: "vitae consectetuer eget rutrum at",
    color: "#a7b83e",
    serializedTo: null,
    subsetId: 14,
  },
  {
    name: "ac tellus semper interdum mauris",
    color: "#977613",
    serializedTo: null,
    subsetId: 14,
  },
  {
    name: "in leo maecenas",
    color: "#04dd08",
    serializedTo: null,
    subsetId: 14,
  },
  {
    name: "enim lorem ipsum",
    color: "#6fb2e6",
    serializedTo: null,
    subsetId: 14,
  },
  {
    name: "duis aliquam convallis nunc proin",
    color: "#fc2518",
    serializedTo: null,
    subsetId: 15,
  },
  {
    name: "vestibulum ante ipsum",
    color: "#9745e4",
    serializedTo: 240,
    subsetId: 15,
  },
  { name: "nec sem", color: "#f0d333", serializedTo: null, subsetId: 15 },
  {
    name: "aliquet massa id lobortis convallis",
    color: "#a43aba",
    serializedTo: null,
    subsetId: 15,
  },
  {
    name: "parturient montes",
    color: "#9dad97",
    serializedTo: null,
    subsetId: 15,
  },
  {
    name: "turpis nec euismod",
    color: "#2ef38c",
    serializedTo: null,
    subsetId: 16,
  },
  {
    name: "quam suspendisse potenti nullam porttitor",
    color: "#ea7022",
    serializedTo: null,
    subsetId: 16,
  },
  {
    name: "nunc viverra dapibus",
    color: "#0c5bbe",
    serializedTo: null,
    subsetId: 16,
  },
  {
    name: "in est risus auctor",
    color: "#540dfb",
    serializedTo: null,
    subsetId: 16,
  },
  {
    name: "eget congue eget semper rutrum",
    color: "#18a09a",
    serializedTo: null,
    subsetId: 16,
  },
  { name: "quisque erat", color: "#1a59d4", serializedTo: 110, subsetId: 17 },
  {
    name: "vestibulum vestibulum ante ipsum",
    color: "#7985d5",
    serializedTo: null,
    subsetId: 17,
  },
  {
    name: "venenatis tristique",
    color: "#55214b",
    serializedTo: 130,
    subsetId: 17,
  },
  {
    name: "mauris ullamcorper",
    color: "#33ece9",
    serializedTo: null,
    subsetId: 17,
  },
  {
    name: "sit amet nulla",
    color: "#6c13b9",
    serializedTo: null,
    subsetId: 17,
  },
  {
    name: "consectetuer adipiscing",
    color: "#3e750e",
    serializedTo: null,
    subsetId: 18,
  },
  { name: "posuere cubilia", color: "#5b56b6", serializedTo: 70, subsetId: 18 },
  { name: "ac diam", color: "#1013f9", serializedTo: null, subsetId: 18 },
  {
    name: "donec diam neque vestibulum eget",
    color: "#b64c2a",
    serializedTo: 120,
    subsetId: 18,
  },
  {
    name: "justo sit amet",
    color: "#06293b",
    serializedTo: null,
    subsetId: 18,
  },
  {
    name: "pede lobortis ligula sit amet",
    color: "#647afa",
    serializedTo: null,
    subsetId: 19,
  },
  {
    name: "lectus vestibulum",
    color: "#2d0dd6",
    serializedTo: null,
    subsetId: 19,
  },
  {
    name: "tortor duis mattis egestas metus",
    color: "#24da1c",
    serializedTo: null,
    subsetId: 19,
  },
  {
    name: "dapibus duis at",
    color: "#6c72cc",
    serializedTo: null,
    subsetId: 19,
  },
  {
    name: "odio donec vitae nisi nam",
    color: "#d59104",
    serializedTo: null,
    subsetId: 19,
  },
  {
    name: "primis in faucibus",
    color: "#d85e0e",
    serializedTo: 140,
    subsetId: 20,
  },
  {
    name: "justo etiam pretium",
    color: "#b20d43",
    serializedTo: null,
    subsetId: 20,
  },
  {
    name: "in eleifend quam",
    color: "#0f0bb3",
    serializedTo: null,
    subsetId: 20,
  },
  {
    name: "varius ut blandit non interdum",
    color: "#3d1991",
    serializedTo: 250,
    subsetId: 20,
  },
  {
    name: "ac leo pellentesque ultrices mattis",
    color: "#3f398f",
    serializedTo: null,
    subsetId: 20,
  },
  { name: "et magnis", color: "#396bf5", serializedTo: null, subsetId: 21 },
  {
    name: "nulla nunc purus",
    color: "#6d4904",
    serializedTo: 20,
    subsetId: 21,
  },
  { name: "ante ipsum", color: "#0c39da", serializedTo: null, subsetId: 21 },
  {
    name: "faucibus orci luctus",
    color: "#68b68f",
    serializedTo: null,
    subsetId: 21,
  },
  {
    name: "hac habitasse platea dictumst etiam",
    color: "#643940",
    serializedTo: null,
    subsetId: 21,
  },
  {
    name: "vestibulum ante ipsum",
    color: "#388604",
    serializedTo: null,
    subsetId: 22,
  },
  {
    name: "elementum eu interdum eu tincidunt",
    color: "#5bff39",
    serializedTo: null,
    subsetId: 22,
  },
  {
    name: "nonummy maecenas tincidunt lacus",
    color: "#945dc5",
    serializedTo: null,
    subsetId: 22,
  },
  {
    name: "eros suspendisse accumsan tortor quis",
    color: "#1e0e31",
    serializedTo: null,
    subsetId: 22,
  },
  {
    name: "lectus pellentesque",
    color: "#ee661c",
    serializedTo: null,
    subsetId: 22,
  },
  {
    name: "vestibulum sit amet cursus",
    color: "#d2d807",
    serializedTo: null,
    subsetId: 23,
  },
  {
    name: "ipsum primis in faucibus",
    color: "#6ad5f0",
    serializedTo: 160,
    subsetId: 23,
  },
  {
    name: "libero nam dui proin leo",
    color: "#a445ef",
    serializedTo: null,
    subsetId: 23,
  },
  {
    name: "neque vestibulum",
    color: "#bf2964",
    serializedTo: null,
    subsetId: 23,
  },
  {
    name: "sapien quis libero",
    color: "#f27cec",
    serializedTo: null,
    subsetId: 23,
  },
  {
    name: "lacus curabitur at ipsum ac",
    color: "#7ece1d",
    serializedTo: null,
    subsetId: 24,
  },
  {
    name: "vivamus in felis",
    color: "#8bf551",
    serializedTo: null,
    subsetId: 24,
  },
  {
    name: "at velit vivamus vel",
    color: "#fc861c",
    serializedTo: null,
    subsetId: 24,
  },
  {
    name: "viverra dapibus nulla suscipit",
    color: "#26a86e",
    serializedTo: 60,
    subsetId: 24,
  },
  {
    name: "tellus semper interdum mauris",
    color: "#e0daa2",
    serializedTo: null,
    subsetId: 24,
  },
  { name: "orci mauris", color: "#05f6df", serializedTo: null, subsetId: 25 },
  {
    name: "mattis odio donec vitae",
    color: "#c8a0af",
    serializedTo: null,
    subsetId: 25,
  },
  {
    name: "mattis nibh ligula nec sem",
    color: "#246d2b",
    serializedTo: null,
    subsetId: 25,
  },
  {
    name: "sed justo pellentesque viverra pede",
    color: "#936105",
    serializedTo: null,
    subsetId: 25,
  },
  {
    name: "aliquet ultrices erat",
    color: "#dcab8a",
    serializedTo: null,
    subsetId: 25,
  },
  {
    name: "phasellus in felis donec semper",
    color: "#34be1c",
    serializedTo: 50,
    subsetId: 26,
  },
  { name: "nunc commodo", color: "#5167c8", serializedTo: null, subsetId: 26 },
  {
    name: "quis justo maecenas rhoncus aliquam",
    color: "#9e4dc5",
    serializedTo: null,
    subsetId: 26,
  },
  {
    name: "vivamus vel nulla eget",
    color: "#46055c",
    serializedTo: null,
    subsetId: 26,
  },
  {
    name: "in quam fringilla rhoncus",
    color: "#b4983d",
    serializedTo: null,
    subsetId: 26,
  },
  {
    name: "justo sit amet sapien dignissim",
    color: "#a04b84",
    serializedTo: null,
    subsetId: 27,
  },
  {
    name: "purus sit amet nulla",
    color: "#4ab8f5",
    serializedTo: null,
    subsetId: 27,
  },
  {
    name: "mollis molestie lorem",
    color: "#030095",
    serializedTo: null,
    subsetId: 27,
  },
  {
    name: "lorem integer tincidunt ante",
    color: "#9610bb",
    serializedTo: null,
    subsetId: 27,
  },
  {
    name: "sodales scelerisque mauris sit amet",
    color: "#e23cd9",
    serializedTo: null,
    subsetId: 27,
  },
  {
    name: "purus phasellus in felis",
    color: "#649a41",
    serializedTo: null,
    subsetId: 28,
  },
  { name: "ut erat", color: "#2b824b", serializedTo: 60, subsetId: 28 },
  {
    name: "vitae consectetuer eget rutrum",
    color: "#425055",
    serializedTo: 30,
    subsetId: 28,
  },
  {
    name: "cum sociis natoque",
    color: "#e94f39",
    serializedTo: null,
    subsetId: 28,
  },
  {
    name: "mauris laoreet ut rhoncus aliquet",
    color: "#111199",
    serializedTo: null,
    subsetId: 28,
  },
  {
    name: "proin at turpis",
    color: "#fd57b7",
    serializedTo: null,
    subsetId: 29,
  },
  {
    name: "aliquam erat volutpat",
    color: "#53e0e3",
    serializedTo: null,
    subsetId: 29,
  },
  {
    name: "platea dictumst",
    color: "#239dc1",
    serializedTo: null,
    subsetId: 29,
  },
  {
    name: "vel augue vestibulum rutrum rutrum",
    color: "#eb506f",
    serializedTo: 30,
    subsetId: 29,
  },
  {
    name: "vivamus in felis eu sapien",
    color: "#fddfc7",
    serializedTo: null,
    subsetId: 29,
  },
  { name: "cubilia curae", color: "#7e056d", serializedTo: null, subsetId: 30 },
  { name: "luctus rutrum", color: "#a65001", serializedTo: null, subsetId: 30 },
  {
    name: "est quam pharetra",
    color: "#006e00",
    serializedTo: null,
    subsetId: 30,
  },
  { name: "quam nec", color: "#9b00a1", serializedTo: 70, subsetId: 30 },
  {
    name: "eget orci vehicula",
    color: "#bebe6c",
    serializedTo: null,
    subsetId: 30,
  },
  {
    name: "montes nascetur ridiculus",
    color: "#f095a7",
    serializedTo: null,
    subsetId: 31,
  },
  {
    name: "justo in hac habitasse",
    color: "#68f9e8",
    serializedTo: null,
    subsetId: 31,
  },
  {
    name: "consequat ut nulla sed",
    color: "#6af763",
    serializedTo: null,
    subsetId: 31,
  },
  {
    name: "magna vulputate luctus",
    color: "#ec51ae",
    serializedTo: null,
    subsetId: 31,
  },
  {
    name: "lacus morbi sem mauris",
    color: "#3326c8",
    serializedTo: null,
    subsetId: 31,
  },
  { name: "lorem quisque", color: "#00887f", serializedTo: 50, subsetId: 32 },
  { name: "tellus nisi", color: "#ab161a", serializedTo: null, subsetId: 32 },
  {
    name: "pretium iaculis justo",
    color: "#80872d",
    serializedTo: null,
    subsetId: 32,
  },
  {
    name: "aliquam quis turpis eget elit",
    color: "#841936",
    serializedTo: 160,
    subsetId: 32,
  },
  {
    name: "odio justo sollicitudin ut",
    color: "#cf9941",
    serializedTo: null,
    subsetId: 32,
  },
  {
    name: "potenti cras in purus eu",
    color: "#5e707a",
    serializedTo: null,
    subsetId: 33,
  },
  {
    name: "odio odio elementum",
    color: "#1362bf",
    serializedTo: null,
    subsetId: 33,
  },
  {
    name: "eros elementum",
    color: "#300f8c",
    serializedTo: null,
    subsetId: 33,
  },
  {
    name: "eget vulputate",
    color: "#2df343",
    serializedTo: null,
    subsetId: 33,
  },
  {
    name: "eget nunc donec",
    color: "#20eb37",
    serializedTo: null,
    subsetId: 33,
  },
  { name: "pede justo", color: "#944c16", serializedTo: null, subsetId: 34 },
  { name: "eget eleifend", color: "#2770a7", serializedTo: null, subsetId: 34 },
  {
    name: "leo maecenas pulvinar",
    color: "#1e0534",
    serializedTo: null,
    subsetId: 34,
  },
  {
    name: "vitae quam suspendisse potenti",
    color: "#f2a100",
    serializedTo: 180,
    subsetId: 34,
  },
  { name: "et tempus", color: "#1a259e", serializedTo: null, subsetId: 34 },
  { name: "velit nec", color: "#843d95", serializedTo: null, subsetId: 35 },
  { name: "in tempus", color: "#160bac", serializedTo: null, subsetId: 35 },
  {
    name: "consequat morbi",
    color: "#831bff",
    serializedTo: null,
    subsetId: 35,
  },
  { name: "rutrum at lorem", color: "#7ff7a4", serializedTo: 30, subsetId: 35 },
  {
    name: "eget tempus vel",
    color: "#4f7749",
    serializedTo: null,
    subsetId: 35,
  },
  {
    name: "morbi non lectus aliquam",
    color: "#36b760",
    serializedTo: null,
    subsetId: 36,
  },
  {
    name: "leo maecenas pulvinar",
    color: "#f792d7",
    serializedTo: null,
    subsetId: 36,
  },
  {
    name: "duis bibendum morbi",
    color: "#032821",
    serializedTo: null,
    subsetId: 36,
  },
  {
    name: "phasellus sit amet erat nulla",
    color: "#202719",
    serializedTo: null,
    subsetId: 36,
  },
  {
    name: "vel nulla eget eros",
    color: "#4c707c",
    serializedTo: null,
    subsetId: 36,
  },
  { name: "in faucibus", color: "#4a697c", serializedTo: null, subsetId: 37 },
  { name: "faucibus orci", color: "#db1c8b", serializedTo: null, subsetId: 37 },
  {
    name: "tempus vivamus",
    color: "#018666",
    serializedTo: null,
    subsetId: 37,
  },
  {
    name: "libero ut massa volutpat",
    color: "#ebcb8e",
    serializedTo: null,
    subsetId: 37,
  },
  {
    name: "elit ac nulla sed",
    color: "#5bc03d",
    serializedTo: null,
    subsetId: 37,
  },
  { name: "sit amet", color: "#db05b5", serializedTo: null, subsetId: 38 },
  { name: "ac neque", color: "#b5fdbd", serializedTo: null, subsetId: 38 },
  { name: "ac enim in", color: "#4ee12c", serializedTo: null, subsetId: 38 },
  {
    name: "faucibus cursus urna ut",
    color: "#7fa295",
    serializedTo: null,
    subsetId: 38,
  },
  {
    name: "eu est congue elementum in",
    color: "#0344e4",
    serializedTo: null,
    subsetId: 38,
  },
  {
    name: "primis in faucibus",
    color: "#451624",
    serializedTo: null,
    subsetId: 39,
  },
  {
    name: "a libero nam dui",
    color: "#f81287",
    serializedTo: null,
    subsetId: 39,
  },
  {
    name: "fusce consequat",
    color: "#b230df",
    serializedTo: null,
    subsetId: 39,
  },
  {
    name: "dis parturient montes",
    color: "#f4f94a",
    serializedTo: null,
    subsetId: 39,
  },
  {
    name: "aliquam quis turpis",
    color: "#7e0a6d",
    serializedTo: null,
    subsetId: 39,
  },
  {
    name: "integer aliquet massa id lobortis",
    color: "#6e87ad",
    serializedTo: null,
    subsetId: 40,
  },
  { name: "gravida nisi", color: "#132718", serializedTo: null, subsetId: 40 },
  {
    name: "maecenas tristique",
    color: "#83e8d3",
    serializedTo: null,
    subsetId: 40,
  },
  { name: "eros viverra", color: "#832559", serializedTo: null, subsetId: 40 },
  {
    name: "placerat praesent blandit nam nulla",
    color: "#902fab",
    serializedTo: null,
    subsetId: 40,
  },
  { name: "odio donec", color: "#2393bf", serializedTo: null, subsetId: 41 },
  {
    name: "pretium iaculis",
    color: "#7875d9",
    serializedTo: null,
    subsetId: 41,
  },
  { name: "nulla integer", color: "#790bec", serializedTo: null, subsetId: 41 },
  { name: "nunc donec", color: "#a29258", serializedTo: null, subsetId: 41 },
  {
    name: "libero rutrum ac lobortis vel",
    color: "#c73486",
    serializedTo: null,
    subsetId: 41,
  },
  {
    name: "tristique tortor eu",
    color: "#d70e58",
    serializedTo: null,
    subsetId: 42,
  },
  {
    name: "lacus curabitur at",
    color: "#d55975",
    serializedTo: null,
    subsetId: 42,
  },
  {
    name: "consectetuer adipiscing",
    color: "#4d0757",
    serializedTo: 60,
    subsetId: 42,
  },
  {
    name: "dis parturient montes nascetur",
    color: "#184d34",
    serializedTo: null,
    subsetId: 42,
  },
  {
    name: "nulla suspendisse potenti cras in",
    color: "#d13bc0",
    serializedTo: null,
    subsetId: 42,
  },
  {
    name: "facilisi cras non velit",
    color: "#4b1180",
    serializedTo: null,
    subsetId: 43,
  },
  {
    name: "ut dolor morbi vel",
    color: "#58abc4",
    serializedTo: null,
    subsetId: 43,
  },
  {
    name: "justo pellentesque viverra",
    color: "#f314fc",
    serializedTo: null,
    subsetId: 43,
  },
  {
    name: "ultrices phasellus",
    color: "#104104",
    serializedTo: null,
    subsetId: 43,
  },
  {
    name: "pulvinar lobortis est",
    color: "#96241d",
    serializedTo: null,
    subsetId: 43,
  },
  {
    name: "ut ultrices vel augue",
    color: "#52d299",
    serializedTo: null,
    subsetId: 44,
  },
  {
    name: "justo pellentesque viverra pede ac",
    color: "#598c6d",
    serializedTo: null,
    subsetId: 44,
  },
  {
    name: "lobortis sapien sapien",
    color: "#b959b2",
    serializedTo: 140,
    subsetId: 44,
  },
  {
    name: "urna ut tellus nulla",
    color: "#7f995b",
    serializedTo: null,
    subsetId: 44,
  },
  {
    name: "eu massa donec",
    color: "#8a1bad",
    serializedTo: null,
    subsetId: 44,
  },
  { name: "rutrum nulla", color: "#a8d690", serializedTo: null, subsetId: 45 },
  {
    name: "iaculis congue vivamus",
    color: "#6b4ecc",
    serializedTo: null,
    subsetId: 45,
  },
  {
    name: "convallis tortor risus dapibus augue",
    color: "#6a07d5",
    serializedTo: null,
    subsetId: 45,
  },
  {
    name: "turpis integer aliquet massa",
    color: "#45797b",
    serializedTo: null,
    subsetId: 45,
  },
  {
    name: "feugiat et eros",
    color: "#312079",
    serializedTo: null,
    subsetId: 45,
  },
  {
    name: "sed accumsan felis ut",
    color: "#cc53b0",
    serializedTo: null,
    subsetId: 46,
  },
  {
    name: "porta volutpat erat quisque",
    color: "#18a1df",
    serializedTo: null,
    subsetId: 46,
  },
  {
    name: "feugiat et eros vestibulum ac",
    color: "#d01153",
    serializedTo: 250,
    subsetId: 46,
  },
  {
    name: "venenatis non sodales sed",
    color: "#d97f34",
    serializedTo: null,
    subsetId: 46,
  },
  {
    name: "sed augue aliquam erat volutpat",
    color: "#66504c",
    serializedTo: null,
    subsetId: 46,
  },
  { name: "aliquam lacus", color: "#4cdb78", serializedTo: null, subsetId: 47 },
  {
    name: "sed ante vivamus",
    color: "#afa162",
    serializedTo: null,
    subsetId: 47,
  },
  {
    name: "interdum in ante",
    color: "#f740c3",
    serializedTo: null,
    subsetId: 47,
  },
  {
    name: "volutpat quam pede lobortis",
    color: "#d1a14b",
    serializedTo: null,
    subsetId: 47,
  },
  {
    name: "integer a nibh",
    color: "#3b1c50",
    serializedTo: null,
    subsetId: 47,
  },
  {
    name: "placerat praesent blandit nam nulla",
    color: "#53351b",
    serializedTo: null,
    subsetId: 48,
  },
  {
    name: "bibendum morbi non quam",
    color: "#851821",
    serializedTo: null,
    subsetId: 48,
  },
  {
    name: "placerat praesent",
    color: "#81e0fd",
    serializedTo: null,
    subsetId: 48,
  },
  {
    name: "dui proin leo odio porttitor",
    color: "#df4034",
    serializedTo: null,
    subsetId: 48,
  },
  {
    name: "natoque penatibus et",
    color: "#6a7824",
    serializedTo: null,
    subsetId: 48,
  },
  {
    name: "etiam justo etiam pretium",
    color: "#ba92ad",
    serializedTo: 70,
    subsetId: 49,
  },
  {
    name: "ipsum primis in faucibus",
    color: "#d3a6b9",
    serializedTo: null,
    subsetId: 49,
  },
  { name: "at lorem", color: "#7ef19a", serializedTo: null, subsetId: 49 },
  { name: "a pede", color: "#f0ab08", serializedTo: null, subsetId: 49 },
  {
    name: "sit amet nunc viverra",
    color: "#bf4d6e",
    serializedTo: null,
    subsetId: 49,
  },
  {
    name: "condimentum id luctus nec molestie",
    color: "#8933b7",
    serializedTo: 170,
    subsetId: 50,
  },
  { name: "nullam sit", color: "#0118f7", serializedTo: null, subsetId: 50 },
  {
    name: "donec ut mauris eget",
    color: "#56477c",
    serializedTo: null,
    subsetId: 50,
  },
  {
    name: "ligula sit amet eleifend",
    color: "#dd17ec",
    serializedTo: null,
    subsetId: 50,
  },
  {
    name: "condimentum neque",
    color: "#9b0119",
    serializedTo: null,
    subsetId: 50,
  },
  {
    name: "non sodales sed",
    color: "#a613c8",
    serializedTo: null,
    subsetId: 51,
  },
  {
    name: "cum sociis natoque penatibus",
    color: "#dec594",
    serializedTo: 50,
    subsetId: 51,
  },
  { name: "nibh in hac", color: "#643f7e", serializedTo: null, subsetId: 51 },
  { name: "iaculis diam", color: "#26a5cd", serializedTo: 150, subsetId: 51 },
  {
    name: "lorem quisque ut erat",
    color: "#4b0d61",
    serializedTo: null,
    subsetId: 51,
  },
  { name: "sapien ut", color: "#40f391", serializedTo: 60, subsetId: 52 },
  {
    name: "a feugiat et eros vestibulum",
    color: "#3286ef",
    serializedTo: null,
    subsetId: 52,
  },
  { name: "at vulputate", color: "#ecf3d9", serializedTo: null, subsetId: 52 },
  {
    name: "proin at turpis",
    color: "#c5d632",
    serializedTo: null,
    subsetId: 52,
  },
  {
    name: "orci luctus et ultrices",
    color: "#cd5a6f",
    serializedTo: null,
    subsetId: 52,
  },
  {
    name: "quis libero nullam sit",
    color: "#b703cb",
    serializedTo: null,
    subsetId: 53,
  },
  {
    name: "odio in hac habitasse",
    color: "#6b7ef0",
    serializedTo: null,
    subsetId: 53,
  },
  {
    name: "massa id lobortis convallis",
    color: "#1fe320",
    serializedTo: 150,
    subsetId: 53,
  },
  {
    name: "dui vel sem sed",
    color: "#695e63",
    serializedTo: null,
    subsetId: 53,
  },
  {
    name: "elementum ligula vehicula",
    color: "#a8391e",
    serializedTo: null,
    subsetId: 53,
  },
  {
    name: "lacinia sapien quis libero nullam",
    color: "#474106",
    serializedTo: null,
    subsetId: 54,
  },
  {
    name: "aliquet ultrices erat tortor",
    color: "#3dd7fe",
    serializedTo: null,
    subsetId: 54,
  },
  { name: "morbi a", color: "#87e394", serializedTo: null, subsetId: 54 },
  {
    name: "nonummy maecenas tincidunt",
    color: "#5f9095",
    serializedTo: null,
    subsetId: 54,
  },
  { name: "odio in", color: "#3dfcdd", serializedTo: null, subsetId: 54 },
  { name: "imperdiet et", color: "#84702b", serializedTo: null, subsetId: 55 },
  {
    name: "donec ut dolor morbi vel",
    color: "#5c183b",
    serializedTo: null,
    subsetId: 55,
  },
  { name: "amet turpis", color: "#de7765", serializedTo: null, subsetId: 55 },
  { name: "odio cras", color: "#bac167", serializedTo: null, subsetId: 55 },
  {
    name: "cubilia curae mauris viverra diam",
    color: "#d921e2",
    serializedTo: 130,
    subsetId: 55,
  },
  {
    name: "cursus vestibulum proin eu",
    color: "#a4af47",
    serializedTo: null,
    subsetId: 56,
  },
  {
    name: "adipiscing lorem",
    color: "#465f96",
    serializedTo: null,
    subsetId: 56,
  },
  { name: "vitae nisl", color: "#8b7dcb", serializedTo: null, subsetId: 56 },
  {
    name: "elementum nullam",
    color: "#bcd14f",
    serializedTo: null,
    subsetId: 56,
  },
  {
    name: "placerat praesent blandit nam",
    color: "#2660ff",
    serializedTo: null,
    subsetId: 56,
  },
  {
    name: "ligula sit amet",
    color: "#75867d",
    serializedTo: null,
    subsetId: 57,
  },
  {
    name: "nulla justo aliquam quis turpis",
    color: "#5fa262",
    serializedTo: null,
    subsetId: 57,
  },
  {
    name: "tincidunt lacus at velit",
    color: "#593a9a",
    serializedTo: null,
    subsetId: 57,
  },
  { name: "eget rutrum", color: "#9f6950", serializedTo: null, subsetId: 57 },
  {
    name: "quis augue luctus",
    color: "#bf0482",
    serializedTo: null,
    subsetId: 57,
  },
  {
    name: "ut at dolor quis odio",
    color: "#dd6c95",
    serializedTo: null,
    subsetId: 58,
  },
  { name: "venenatis non", color: "#10a64a", serializedTo: null, subsetId: 58 },
  {
    name: "sit amet nulla",
    color: "#9626af",
    serializedTo: null,
    subsetId: 58,
  },
  {
    name: "dolor sit amet consectetuer adipiscing",
    color: "#b08941",
    serializedTo: null,
    subsetId: 58,
  },
  {
    name: "consectetuer adipiscing elit",
    color: "#92632e",
    serializedTo: null,
    subsetId: 58,
  },
  { name: "duis mattis", color: "#70babc", serializedTo: null, subsetId: 59 },
  {
    name: "tempor convallis nulla neque",
    color: "#5523c0",
    serializedTo: null,
    subsetId: 59,
  },
  { name: "leo rhoncus", color: "#61b854", serializedTo: null, subsetId: 59 },
  {
    name: "arcu adipiscing molestie hendrerit at",
    color: "#893398",
    serializedTo: null,
    subsetId: 59,
  },
  { name: "sed ante", color: "#7c302b", serializedTo: null, subsetId: 59 },
  {
    name: "dolor sit amet consectetuer",
    color: "#16f412",
    serializedTo: null,
    subsetId: 60,
  },
  { name: "augue quam", color: "#7617bc", serializedTo: 250, subsetId: 60 },
  {
    name: "consequat metus sapien ut nunc",
    color: "#49e664",
    serializedTo: null,
    subsetId: 60,
  },
  {
    name: "purus aliquet at feugiat",
    color: "#b1887e",
    serializedTo: null,
    subsetId: 60,
  },
  {
    name: "habitasse platea dictumst etiam faucibus",
    color: "#8f41a5",
    serializedTo: null,
    subsetId: 60,
  },
  {
    name: "ultrices posuere cubilia",
    color: "#e851d5",
    serializedTo: null,
    subsetId: 61,
  },
  { name: "risus dapibus", color: "#b59284", serializedTo: null, subsetId: 61 },
  {
    name: "leo odio condimentum id luctus",
    color: "#fa6417",
    serializedTo: null,
    subsetId: 61,
  },
  { name: "quis justo", color: "#0618ab", serializedTo: null, subsetId: 61 },
  {
    name: "nisi vulputate nonummy",
    color: "#de027f",
    serializedTo: null,
    subsetId: 61,
  },
  {
    name: "vulputate ut ultrices vel",
    color: "#5d44ba",
    serializedTo: null,
    subsetId: 62,
  },
  {
    name: "turpis a pede posuere nonummy",
    color: "#86fdf5",
    serializedTo: null,
    subsetId: 62,
  },
  {
    name: "aliquet ultrices erat tortor",
    color: "#27e4a5",
    serializedTo: null,
    subsetId: 62,
  },
  {
    name: "felis sed interdum venenatis",
    color: "#270ecc",
    serializedTo: null,
    subsetId: 62,
  },
  { name: "ultrices enim", color: "#641cbd", serializedTo: null, subsetId: 62 },
  { name: "pulvinar sed", color: "#ef2588", serializedTo: null, subsetId: 63 },
  {
    name: "varius integer ac leo pellentesque",
    color: "#ad2960",
    serializedTo: null,
    subsetId: 63,
  },
  { name: "purus aliquet", color: "#d8cdba", serializedTo: null, subsetId: 63 },
  {
    name: "malesuada in imperdiet et",
    color: "#fe0bf6",
    serializedTo: null,
    subsetId: 63,
  },
  {
    name: "augue vestibulum rutrum",
    color: "#e01b07",
    serializedTo: null,
    subsetId: 63,
  },
  { name: "tempus vel", color: "#31c17c", serializedTo: null, subsetId: 64 },
  { name: "in tempus", color: "#30f802", serializedTo: null, subsetId: 64 },
  {
    name: "iaculis congue vivamus metus",
    color: "#913f99",
    serializedTo: null,
    subsetId: 64,
  },
  {
    name: "sapien cursus vestibulum proin eu",
    color: "#958671",
    serializedTo: null,
    subsetId: 64,
  },
  {
    name: "pede posuere nonummy integer",
    color: "#d8a8e4",
    serializedTo: null,
    subsetId: 64,
  },
  {
    name: "nec nisi vulputate nonummy",
    color: "#54cdd4",
    serializedTo: null,
    subsetId: 65,
  },
  {
    name: "imperdiet nullam orci",
    color: "#a956ac",
    serializedTo: null,
    subsetId: 65,
  },
  {
    name: "posuere cubilia curae",
    color: "#d1437b",
    serializedTo: null,
    subsetId: 65,
  },
  {
    name: "odio in hac habitasse",
    color: "#6091e1",
    serializedTo: null,
    subsetId: 65,
  },
  {
    name: "duis at velit eu",
    color: "#c03a41",
    serializedTo: null,
    subsetId: 65,
  },
  {
    name: "quam fringilla rhoncus mauris",
    color: "#26af6f",
    serializedTo: null,
    subsetId: 66,
  },
  {
    name: "diam cras pellentesque volutpat",
    color: "#7ed926",
    serializedTo: null,
    subsetId: 66,
  },
  {
    name: "praesent id massa id",
    color: "#c0e4c1",
    serializedTo: 150,
    subsetId: 66,
  },
  { name: "mus etiam vel", color: "#db0e5b", serializedTo: null, subsetId: 66 },
  {
    name: "varius integer ac",
    color: "#175853",
    serializedTo: null,
    subsetId: 66,
  },
  {
    name: "mi nulla ac enim in",
    color: "#9f6d5c",
    serializedTo: null,
    subsetId: 67,
  },
  {
    name: "et tempus semper",
    color: "#8774e2",
    serializedTo: null,
    subsetId: 67,
  },
  {
    name: "vulputate elementum",
    color: "#cc98fa",
    serializedTo: null,
    subsetId: 67,
  },
  {
    name: "id pretium iaculis diam",
    color: "#79ae47",
    serializedTo: 100,
    subsetId: 67,
  },
  {
    name: "nullam porttitor lacus at turpis",
    color: "#a9d594",
    serializedTo: null,
    subsetId: 67,
  },
  {
    name: "neque libero convallis eget eleifend",
    color: "#1cd638",
    serializedTo: null,
    subsetId: 68,
  },
  {
    name: "odio condimentum id luctus",
    color: "#074dbe",
    serializedTo: null,
    subsetId: 68,
  },
  { name: "ut odio", color: "#475b0a", serializedTo: null, subsetId: 68 },
  {
    name: "eget eleifend luctus ultricies",
    color: "#1d3f63",
    serializedTo: null,
    subsetId: 68,
  },
  {
    name: "eleifend luctus ultricies eu nibh",
    color: "#8ed2e7",
    serializedTo: null,
    subsetId: 68,
  },
  {
    name: "cursus vestibulum proin eu",
    color: "#671b4a",
    serializedTo: 30,
    subsetId: 69,
  },
  {
    name: "pede justo lacinia",
    color: "#eda005",
    serializedTo: null,
    subsetId: 69,
  },
  {
    name: "in porttitor pede",
    color: "#95b647",
    serializedTo: null,
    subsetId: 69,
  },
  {
    name: "porta volutpat quam pede",
    color: "#6901d5",
    serializedTo: null,
    subsetId: 69,
  },
  {
    name: "mauris ullamcorper purus sit amet",
    color: "#484765",
    serializedTo: null,
    subsetId: 69,
  },
  { name: "quis justo", color: "#a4f764", serializedTo: null, subsetId: 70 },
  {
    name: "curae duis faucibus accumsan odio",
    color: "#5817ee",
    serializedTo: null,
    subsetId: 70,
  },
  {
    name: "donec semper sapien a",
    color: "#3142fd",
    serializedTo: null,
    subsetId: 70,
  },
  {
    name: "vulputate nonummy maecenas tincidunt",
    color: "#2a6e92",
    serializedTo: null,
    subsetId: 70,
  },
  {
    name: "convallis eget eleifend",
    color: "#49c879",
    serializedTo: null,
    subsetId: 70,
  },
  {
    name: "maecenas rhoncus aliquam",
    color: "#4f7a01",
    serializedTo: null,
    subsetId: 71,
  },
  {
    name: "eget massa tempor",
    color: "#d5dce4",
    serializedTo: null,
    subsetId: 71,
  },
  {
    name: "augue vestibulum rutrum rutrum neque",
    color: "#6ce632",
    serializedTo: null,
    subsetId: 71,
  },
  {
    name: "quam pharetra magna ac consequat",
    color: "#b8f5ef",
    serializedTo: null,
    subsetId: 71,
  },
  {
    name: "ante ipsum primis in",
    color: "#119ac2",
    serializedTo: null,
    subsetId: 71,
  },
  {
    name: "tristique fusce congue diam id",
    color: "#9ec4bf",
    serializedTo: null,
    subsetId: 72,
  },
  {
    name: "porta volutpat quam pede",
    color: "#b35231",
    serializedTo: null,
    subsetId: 72,
  },
  {
    name: "praesent blandit lacinia",
    color: "#94661e",
    serializedTo: null,
    subsetId: 72,
  },
  {
    name: "vitae mattis nibh",
    color: "#279c5a",
    serializedTo: null,
    subsetId: 72,
  },
  {
    name: "lectus in quam fringilla",
    color: "#68e81b",
    serializedTo: 70,
    subsetId: 72,
  },
  {
    name: "magna vestibulum aliquet ultrices",
    color: "#56ca55",
    serializedTo: null,
    subsetId: 73,
  },
  {
    name: "ultrices enim lorem ipsum dolor",
    color: "#5d5ee3",
    serializedTo: null,
    subsetId: 73,
  },
  {
    name: "pretium quis lectus suspendisse",
    color: "#a01695",
    serializedTo: null,
    subsetId: 73,
  },
  {
    name: "adipiscing molestie",
    color: "#01ce81",
    serializedTo: null,
    subsetId: 73,
  },
  {
    name: "ante nulla justo aliquam quis",
    color: "#4b14ba",
    serializedTo: null,
    subsetId: 73,
  },
  {
    name: "sed accumsan felis",
    color: "#b5fbfe",
    serializedTo: null,
    subsetId: 74,
  },
  { name: "rutrum neque", color: "#4d7f2c", serializedTo: null, subsetId: 74 },
  {
    name: "ultrices posuere",
    color: "#a418fd",
    serializedTo: null,
    subsetId: 74,
  },
  { name: "nulla quisque", color: "#aa1fc0", serializedTo: 180, subsetId: 74 },
  { name: "ligula sit", color: "#e379ff", serializedTo: null, subsetId: 74 },
  {
    name: "quam sollicitudin",
    color: "#6d40c5",
    serializedTo: 20,
    subsetId: 75,
  },
  {
    name: "dui luctus rutrum nulla",
    color: "#a9dab8",
    serializedTo: null,
    subsetId: 75,
  },
  {
    name: "nunc proin at turpis",
    color: "#014ac1",
    serializedTo: null,
    subsetId: 75,
  },
  {
    name: "diam in magna bibendum imperdiet",
    color: "#19bc45",
    serializedTo: null,
    subsetId: 75,
  },
  {
    name: "eu felis fusce",
    color: "#164adf",
    serializedTo: null,
    subsetId: 75,
  },
  { name: "ac nibh fusce", color: "#f97a7f", serializedTo: 90, subsetId: 76 },
  {
    name: "eleifend luctus ultricies eu",
    color: "#bf2629",
    serializedTo: null,
    subsetId: 76,
  },
  {
    name: "nam tristique tortor eu pede",
    color: "#914eb6",
    serializedTo: null,
    subsetId: 76,
  },
  {
    name: "orci luctus et ultrices posuere",
    color: "#49b66b",
    serializedTo: null,
    subsetId: 76,
  },
  {
    name: "potenti in eleifend",
    color: "#38b83d",
    serializedTo: 10,
    subsetId: 76,
  },
  { name: "tempus semper", color: "#b298ba", serializedTo: 230, subsetId: 77 },
  {
    name: "sed interdum venenatis",
    color: "#d0f534",
    serializedTo: null,
    subsetId: 77,
  },
  {
    name: "turpis enim blandit mi",
    color: "#f42b72",
    serializedTo: null,
    subsetId: 77,
  },
  {
    name: "nunc donec quis",
    color: "#da2f0f",
    serializedTo: null,
    subsetId: 77,
  },
  {
    name: "etiam justo etiam pretium",
    color: "#5c57b6",
    serializedTo: null,
    subsetId: 77,
  },
  {
    name: "sapien cursus vestibulum proin eu",
    color: "#7b32c4",
    serializedTo: null,
    subsetId: 78,
  },
  { name: "urna ut", color: "#b06b00", serializedTo: null, subsetId: 78 },
  {
    name: "praesent id massa id",
    color: "#62be79",
    serializedTo: null,
    subsetId: 78,
  },
  {
    name: "non velit nec nisi vulputate",
    color: "#708480",
    serializedTo: null,
    subsetId: 78,
  },
  {
    name: "blandit nam nulla integer",
    color: "#4eff33",
    serializedTo: null,
    subsetId: 78,
  },
  {
    name: "sollicitudin ut",
    color: "#42b425",
    serializedTo: 160,
    subsetId: 79,
  },
  { name: "aenean lectus", color: "#ae2e4f", serializedTo: null, subsetId: 79 },
  {
    name: "nonummy maecenas tincidunt lacus",
    color: "#a510cc",
    serializedTo: null,
    subsetId: 79,
  },
  { name: "odio donec", color: "#fdb97b", serializedTo: null, subsetId: 79 },
  {
    name: "scelerisque mauris",
    color: "#083701",
    serializedTo: null,
    subsetId: 79,
  },
  {
    name: "primis in faucibus",
    color: "#f28235",
    serializedTo: null,
    subsetId: 80,
  },
  { name: "ac est", color: "#ff0fd1", serializedTo: null, subsetId: 80 },
  {
    name: "ultrices posuere cubilia curae",
    color: "#85d042",
    serializedTo: null,
    subsetId: 80,
  },
  {
    name: "dictumst etiam faucibus cursus",
    color: "#02c1bd",
    serializedTo: null,
    subsetId: 80,
  },
  {
    name: "sapien sapien non",
    color: "#1a9c89",
    serializedTo: null,
    subsetId: 80,
  },
  {
    name: "eu orci mauris lacinia sapien",
    color: "#37f151",
    serializedTo: null,
    subsetId: 81,
  },
  {
    name: "dapibus at diam nam",
    color: "#99eb5f",
    serializedTo: null,
    subsetId: 81,
  },
  {
    name: "nunc donec quis",
    color: "#097427",
    serializedTo: 140,
    subsetId: 81,
  },
  { name: "volutpat dui", color: "#1bc97e", serializedTo: null, subsetId: 81 },
  { name: "luctus rutrum", color: "#e8f398", serializedTo: 120, subsetId: 81 },
  { name: "nec euismod", color: "#929b43", serializedTo: null, subsetId: 82 },
  { name: "quam sapien", color: "#ee5dfb", serializedTo: null, subsetId: 82 },
  {
    name: "non lectus aliquam",
    color: "#4e4901",
    serializedTo: null,
    subsetId: 82,
  },
  { name: "duis mattis", color: "#c2585b", serializedTo: null, subsetId: 82 },
  {
    name: "non interdum in ante vestibulum",
    color: "#1bc38d",
    serializedTo: null,
    subsetId: 82,
  },
  {
    name: "dapibus at diam nam",
    color: "#60a289",
    serializedTo: null,
    subsetId: 83,
  },
  {
    name: "eros suspendisse",
    color: "#db0858",
    serializedTo: null,
    subsetId: 83,
  },
  {
    name: "est risus auctor sed tristique",
    color: "#c0dd30",
    serializedTo: null,
    subsetId: 83,
  },
  {
    name: "quam pharetra magna",
    color: "#7a3ae6",
    serializedTo: null,
    subsetId: 83,
  },
  {
    name: "ac neque duis bibendum morbi",
    color: "#2fac14",
    serializedTo: null,
    subsetId: 83,
  },
  {
    name: "lorem vitae mattis",
    color: "#073d57",
    serializedTo: null,
    subsetId: 84,
  },
  { name: "aliquam quis", color: "#d474cc", serializedTo: 120, subsetId: 84 },
  {
    name: "eleifend donec ut",
    color: "#ff9d57",
    serializedTo: null,
    subsetId: 84,
  },
  {
    name: "erat tortor sollicitudin mi",
    color: "#ab0bc1",
    serializedTo: 240,
    subsetId: 84,
  },
  {
    name: "amet nulla quisque arcu",
    color: "#2516ed",
    serializedTo: null,
    subsetId: 84,
  },
  {
    name: "vel sem sed sagittis",
    color: "#a2c2e7",
    serializedTo: null,
    subsetId: 85,
  },
  {
    name: "mauris non ligula pellentesque",
    color: "#56c9e2",
    serializedTo: null,
    subsetId: 85,
  },
  {
    name: "integer pede justo lacinia",
    color: "#5b2478",
    serializedTo: null,
    subsetId: 85,
  },
  {
    name: "vestibulum ante",
    color: "#70a25b",
    serializedTo: null,
    subsetId: 85,
  },
  { name: "duis faucibus", color: "#82b957", serializedTo: null, subsetId: 85 },
  {
    name: "luctus et ultrices posuere cubilia",
    color: "#039444",
    serializedTo: null,
    subsetId: 86,
  },
  {
    name: "sociis natoque penatibus et magnis",
    color: "#856da1",
    serializedTo: null,
    subsetId: 86,
  },
  {
    name: "faucibus orci luctus et ultrices",
    color: "#851afe",
    serializedTo: null,
    subsetId: 86,
  },
  { name: "non pretium", color: "#05cdb7", serializedTo: 230, subsetId: 86 },
  {
    name: "turpis a pede posuere",
    color: "#b5da6a",
    serializedTo: 120,
    subsetId: 86,
  },
  {
    name: "eget eleifend luctus",
    color: "#c25cd1",
    serializedTo: null,
    subsetId: 87,
  },
  {
    name: "sollicitudin mi sit amet lobortis",
    color: "#67fc7d",
    serializedTo: 110,
    subsetId: 87,
  },
  {
    name: "vestibulum ante ipsum primis",
    color: "#5c8661",
    serializedTo: null,
    subsetId: 87,
  },
  {
    name: "pellentesque eget nunc",
    color: "#d311fb",
    serializedTo: null,
    subsetId: 87,
  },
  {
    name: "potenti nullam porttitor lacus",
    color: "#d978dc",
    serializedTo: null,
    subsetId: 87,
  },
  {
    name: "lorem integer tincidunt",
    color: "#f66b8f",
    serializedTo: null,
    subsetId: 88,
  },
  {
    name: "hac habitasse platea dictumst",
    color: "#ec3670",
    serializedTo: null,
    subsetId: 88,
  },
  {
    name: "consequat varius integer ac leo",
    color: "#303ed1",
    serializedTo: null,
    subsetId: 88,
  },
  {
    name: "at nunc commodo placerat",
    color: "#9cb15d",
    serializedTo: null,
    subsetId: 88,
  },
  {
    name: "orci luctus et ultrices posuere",
    color: "#ce400b",
    serializedTo: null,
    subsetId: 88,
  },
  {
    name: "lectus suspendisse",
    color: "#90e42a",
    serializedTo: null,
    subsetId: 89,
  },
  {
    name: "nulla elit ac nulla sed",
    color: "#991c34",
    serializedTo: null,
    subsetId: 89,
  },
  {
    name: "quis lectus suspendisse",
    color: "#456c18",
    serializedTo: null,
    subsetId: 89,
  },
  {
    name: "volutpat quam pede",
    color: "#1df43c",
    serializedTo: null,
    subsetId: 89,
  },
  { name: "a pede", color: "#aa20a2", serializedTo: null, subsetId: 89 },
  {
    name: "arcu libero rutrum ac",
    color: "#e9c93e",
    serializedTo: null,
    subsetId: 90,
  },
  {
    name: "vitae consectetuer",
    color: "#278745",
    serializedTo: null,
    subsetId: 90,
  },
  {
    name: "augue vel accumsan tellus",
    color: "#1971fe",
    serializedTo: null,
    subsetId: 90,
  },
  {
    name: "ac diam cras pellentesque",
    color: "#87f24e",
    serializedTo: null,
    subsetId: 90,
  },
  {
    name: "mattis pulvinar nulla pede ullamcorper",
    color: "#a93f02",
    serializedTo: null,
    subsetId: 90,
  },
  {
    name: "arcu libero rutrum ac lobortis",
    color: "#5ccb78",
    serializedTo: null,
    subsetId: 91,
  },
  { name: "congue eget", color: "#dd43b0", serializedTo: null, subsetId: 91 },
  { name: "dui maecenas", color: "#e471a7", serializedTo: null, subsetId: 91 },
  {
    name: "est donec odio justo sollicitudin",
    color: "#45d630",
    serializedTo: null,
    subsetId: 91,
  },
  {
    name: "sapien arcu sed augue aliquam",
    color: "#8d8064",
    serializedTo: null,
    subsetId: 91,
  },
  {
    name: "semper rutrum nulla nunc",
    color: "#ec2ef9",
    serializedTo: null,
    subsetId: 92,
  },
  {
    name: "non mauris morbi non",
    color: "#1cb087",
    serializedTo: null,
    subsetId: 92,
  },
  {
    name: "quis tortor id nulla ultrices",
    color: "#703cf1",
    serializedTo: null,
    subsetId: 92,
  },
  {
    name: "posuere nonummy",
    color: "#ba1623",
    serializedTo: null,
    subsetId: 92,
  },
  {
    name: "congue elementum",
    color: "#98138b",
    serializedTo: null,
    subsetId: 92,
  },
  {
    name: "cras pellentesque volutpat",
    color: "#b7e230",
    serializedTo: null,
    subsetId: 93,
  },
  {
    name: "elementum eu interdum eu",
    color: "#0317dd",
    serializedTo: null,
    subsetId: 93,
  },
  {
    name: "sed lacus morbi sem mauris",
    color: "#7198c3",
    serializedTo: 20,
    subsetId: 93,
  },
  {
    name: "consectetuer adipiscing elit",
    color: "#0f1327",
    serializedTo: null,
    subsetId: 93,
  },
  {
    name: "sociis natoque penatibus",
    color: "#a47fb0",
    serializedTo: null,
    subsetId: 93,
  },
  {
    name: "ipsum primis in faucibus orci",
    color: "#59363d",
    serializedTo: null,
    subsetId: 94,
  },
  { name: "dolor morbi", color: "#368737", serializedTo: null, subsetId: 94 },
  {
    name: "luctus nec molestie sed justo",
    color: "#291762",
    serializedTo: null,
    subsetId: 94,
  },
  { name: "consequat ut", color: "#e68b85", serializedTo: 250, subsetId: 94 },
  {
    name: "orci luctus et",
    color: "#29eec0",
    serializedTo: null,
    subsetId: 94,
  },
  {
    name: "eros vestibulum",
    color: "#bdc46a",
    serializedTo: null,
    subsetId: 95,
  },
  {
    name: "morbi non quam nec dui",
    color: "#1a86be",
    serializedTo: 50,
    subsetId: 95,
  },
  {
    name: "justo in blandit",
    color: "#1d0cd0",
    serializedTo: null,
    subsetId: 95,
  },
  {
    name: "nulla ut erat id mauris",
    color: "#86538f",
    serializedTo: null,
    subsetId: 95,
  },
  {
    name: "aliquam erat volutpat in",
    color: "#c07e69",
    serializedTo: null,
    subsetId: 95,
  },
  {
    name: "metus sapien ut nunc",
    color: "#1bb2f5",
    serializedTo: null,
    subsetId: 96,
  },
  { name: "justo maecenas", color: "#40ef13", serializedTo: 50, subsetId: 96 },
  {
    name: "dictumst aliquam augue",
    color: "#272b83",
    serializedTo: null,
    subsetId: 96,
  },
  {
    name: "ipsum aliquam non mauris morbi",
    color: "#49b85e",
    serializedTo: null,
    subsetId: 96,
  },
  {
    name: "ultricies eu nibh quisque id",
    color: "#b9bfc8",
    serializedTo: null,
    subsetId: 96,
  },
  {
    name: "quis augue luctus tincidunt",
    color: "#424a94",
    serializedTo: null,
    subsetId: 97,
  },
  {
    name: "in consequat ut nulla",
    color: "#3b2868",
    serializedTo: null,
    subsetId: 97,
  },
  { name: "hac habitasse", color: "#dfe42d", serializedTo: null, subsetId: 97 },
  {
    name: "rutrum nulla tellus in sagittis",
    color: "#108155",
    serializedTo: 140,
    subsetId: 97,
  },
  {
    name: "nec molestie sed",
    color: "#b049a3",
    serializedTo: null,
    subsetId: 97,
  },
  {
    name: "blandit nam nulla integer pede",
    color: "#a192ba",
    serializedTo: null,
    subsetId: 98,
  },
  {
    name: "volutpat in congue",
    color: "#340cf2",
    serializedTo: null,
    subsetId: 98,
  },
  {
    name: "magna ac consequat metus sapien",
    color: "#ca7ab7",
    serializedTo: null,
    subsetId: 98,
  },
  {
    name: "blandit lacinia erat vestibulum sed",
    color: "#aab3da",
    serializedTo: null,
    subsetId: 98,
  },
  {
    name: "pretium iaculis diam",
    color: "#86eb94",
    serializedTo: null,
    subsetId: 98,
  },
  {
    name: "nunc vestibulum",
    color: "#e5231f",
    serializedTo: null,
    subsetId: 99,
  },
  {
    name: "ultrices mattis odio donec vitae",
    color: "#0d4e56",
    serializedTo: 230,
    subsetId: 99,
  },
  {
    name: "donec quis orci eget orci",
    color: "#190a19",
    serializedTo: null,
    subsetId: 99,
  },
  { name: "vitae ipsum", color: "#784aff", serializedTo: null, subsetId: 99 },
  {
    name: "vestibulum ac est lacinia",
    color: "#85097c",
    serializedTo: null,
    subsetId: 99,
  },
  {
    name: "in hac habitasse platea dictumst",
    color: "#f21ebe",
    serializedTo: null,
    subsetId: 100,
  },
  {
    name: "vulputate elementum nullam varius nulla",
    color: "#89677d",
    serializedTo: 70,
    subsetId: 100,
  },
  {
    name: "turpis sed ante vivamus tortor",
    color: "#6ccff2",
    serializedTo: null,
    subsetId: 100,
  },
  { name: "ante ipsum", color: "#81d23d", serializedTo: null, subsetId: 100 },
  {
    name: "ante ipsum primis in faucibus",
    color: "#ef58b0",
    serializedTo: null,
    subsetId: 100,
  },
];

module.exports = series;
