const sets = [
  { name: "massa volutpat convallis", year: 2016, leagueId: 1, brandId: 1 },
  {
    name: "pede lobortis ligula sit amet",
    year: 2015,
    leagueId: 1,
    brandId: 1,
  },
  { name: "nisi eu orci mauris lacinia", year: 2017, leagueId: 1, brandId: 1 },
  {
    name: "sapien cursus vestibulum proin",
    year: 2019,
    leagueId: 1,
    brandId: 1,
  },
  {
    name: "justo in blandit ultrices enim",
    year: 2020,
    leagueId: 1,
    brandId: 1,
  },
  {
    name: "metus arcu adipiscing molestie",
    year: 2019,
    leagueId: 1,
    brandId: 1,
  },
  { name: "orci luctus et ultrices", year: 2019, leagueId: 1, brandId: 1 },
  {
    name: "platea dictumst morbi vestibulum velit",
    year: 2019,
    leagueId: 1,
    brandId: 1,
  },
  { name: "congue eget", year: 2016, leagueId: 1, brandId: 1 },
  { name: "pede justo eu massa donec", year: 2019, leagueId: 1, brandId: 1 },
  { name: "eget rutrum at lorem integer", year: 2017, leagueId: 1, brandId: 1 },
  { name: "nonummy integer", year: 2019, leagueId: 1, brandId: 1 },
  { name: "sed tristique in tempus sit", year: 2017, leagueId: 1, brandId: 1 },
  {
    name: "mus vivamus vestibulum sagittis",
    year: 2015,
    leagueId: 1,
    brandId: 1,
  },
  { name: "purus sit amet", year: 2019, leagueId: 1, brandId: 1 },
  { name: "eu felis fusce posuere felis", year: 2015, leagueId: 1, brandId: 1 },
  { name: "nisl duis ac", year: 2017, leagueId: 1, brandId: 1 },
  {
    name: "risus semper porta volutpat quam",
    year: 2020,
    leagueId: 1,
    brandId: 1,
  },
  { name: "egestas metus aenean", year: 2016, leagueId: 1, brandId: 1 },
  {
    name: "mattis pulvinar nulla pede ullamcorper",
    year: 2017,
    leagueId: 1,
    brandId: 1,
  },
  {
    name: "placerat praesent blandit nam nulla",
    year: 2019,
    leagueId: 1,
    brandId: 1,
  },
  { name: "pede ullamcorper augue", year: 2015, leagueId: 1, brandId: 1 },
  { name: "faucibus cursus urna", year: 2017, leagueId: 1, brandId: 1 },
  {
    name: "integer pede justo lacinia eget",
    year: 2015,
    leagueId: 1,
    brandId: 1,
  },
  { name: "nulla integer pede justo", year: 2018, leagueId: 1, brandId: 1 },
];

module.exports = sets;
