const subsets = [
  { name: "turpis sed", cardQuantity: 100, setId: 1 },
  { name: "tortor risus dapibus augue", cardQuantity: 100, setId: 1 },
  { name: "dictumst morbi", cardQuantity: 100, setId: 1 },
  { name: "at ipsum ac tellus", cardQuantity: 100, setId: 1 },
  { name: "nulla elit ac nulla", cardQuantity: 100, setId: 1 },
  { name: "sit amet turpis elementum", cardQuantity: 100, setId: 2 },
  { name: "leo pellentesque ultrices mattis", cardQuantity: 100, setId: 2 },
  { name: "nec nisi volutpat", cardQuantity: 100, setId: 2 },
  { name: "quis tortor id nulla", cardQuantity: 100, setId: 2 },
  { name: "duis at velit", cardQuantity: 100, setId: 2 },
  { name: "habitasse platea dictumst", cardQuantity: 100, setId: 3 },
  { name: "lacus morbi", cardQuantity: 100, setId: 3 },
  { name: "lectus aliquam sit", cardQuantity: 100, setId: 3 },
  { name: "amet turpis", cardQuantity: 100, setId: 3 },
  { name: "blandit mi in porttitor", cardQuantity: 100, setId: 3 },
  { name: "interdum venenatis turpis enim", cardQuantity: 100, setId: 4 },
  { name: "nunc rhoncus dui", cardQuantity: 100, setId: 4 },
  { name: "ante vivamus", cardQuantity: 100, setId: 4 },
  { name: "sodales sed tincidunt eu", cardQuantity: 100, setId: 4 },
  { name: "ornare consequat lectus", cardQuantity: 100, setId: 4 },
  { name: "etiam vel augue", cardQuantity: 100, setId: 5 },
  { name: "erat tortor", cardQuantity: 100, setId: 5 },
  { name: "semper est quam pharetra", cardQuantity: 100, setId: 5 },
  { name: "nullam orci pede", cardQuantity: 100, setId: 5 },
  { name: "eu interdum", cardQuantity: 100, setId: 5 },
  { name: "augue vel accumsan", cardQuantity: 100, setId: 6 },
  { name: "amet turpis elementum ligula", cardQuantity: 100, setId: 6 },
  { name: "leo rhoncus", cardQuantity: 100, setId: 6 },
  { name: "scelerisque quam", cardQuantity: 100, setId: 6 },
  { name: "at turpis", cardQuantity: 100, setId: 6 },
  { name: "eleifend donec ut dolor", cardQuantity: 100, setId: 7 },
  { name: "consequat lectus in", cardQuantity: 100, setId: 7 },
  { name: "morbi odio odio elementum", cardQuantity: 100, setId: 7 },
  { name: "vivamus tortor duis mattis", cardQuantity: 100, setId: 7 },
  { name: "eleifend quam", cardQuantity: 100, setId: 7 },
  { name: "volutpat in congue", cardQuantity: 100, setId: 8 },
  { name: "quam nec dui", cardQuantity: 100, setId: 8 },
  { name: "id pretium iaculis", cardQuantity: 100, setId: 8 },
  { name: "praesent blandit lacinia", cardQuantity: 100, setId: 8 },
  { name: "magna bibendum imperdiet", cardQuantity: 100, setId: 8 },
  { name: "lobortis est phasellus sit", cardQuantity: 100, setId: 9 },
  { name: "quisque arcu", cardQuantity: 100, setId: 9 },
  { name: "justo in hac", cardQuantity: 100, setId: 9 },
  { name: "felis sed", cardQuantity: 100, setId: 9 },
  { name: "nec molestie sed justo", cardQuantity: 100, setId: 9 },
  { name: "pretium iaculis", cardQuantity: 100, setId: 10 },
  { name: "sed interdum", cardQuantity: 100, setId: 10 },
  { name: "hac habitasse", cardQuantity: 100, setId: 10 },
  { name: "ac nulla sed vel", cardQuantity: 100, setId: 10 },
  { name: "nulla ultrices", cardQuantity: 100, setId: 10 },
  { name: "convallis nunc proin at", cardQuantity: 100, setId: 11 },
  { name: "sit amet eleifend", cardQuantity: 100, setId: 11 },
  { name: "tempor turpis nec", cardQuantity: 100, setId: 11 },
  { name: "maecenas tincidunt lacus at", cardQuantity: 100, setId: 11 },
  { name: "interdum eu tincidunt in", cardQuantity: 100, setId: 11 },
  { name: "laoreet ut rhoncus", cardQuantity: 100, setId: 12 },
  { name: "mattis egestas metus", cardQuantity: 100, setId: 12 },
  { name: "felis ut at dolor", cardQuantity: 100, setId: 12 },
  { name: "nulla sed vel", cardQuantity: 100, setId: 12 },
  { name: "tortor risus dapibus", cardQuantity: 100, setId: 12 },
  { name: "lectus in", cardQuantity: 100, setId: 13 },
  { name: "ut suscipit a", cardQuantity: 100, setId: 13 },
  { name: "massa id nisl", cardQuantity: 100, setId: 13 },
  { name: "congue vivamus metus arcu", cardQuantity: 100, setId: 13 },
  { name: "quam fringilla", cardQuantity: 100, setId: 13 },
  { name: "adipiscing lorem vitae mattis", cardQuantity: 100, setId: 14 },
  { name: "vestibulum ante ipsum", cardQuantity: 100, setId: 14 },
  { name: "lacinia eget tincidunt", cardQuantity: 100, setId: 14 },
  { name: "amet consectetuer", cardQuantity: 100, setId: 14 },
  { name: "in porttitor pede justo", cardQuantity: 100, setId: 14 },
  { name: "volutpat erat quisque erat", cardQuantity: 100, setId: 15 },
  { name: "rutrum neque", cardQuantity: 100, setId: 15 },
  { name: "elit sodales", cardQuantity: 100, setId: 15 },
  { name: "arcu libero rutrum", cardQuantity: 100, setId: 15 },
  { name: "ut massa quis", cardQuantity: 100, setId: 15 },
  { name: "donec diam neque", cardQuantity: 100, setId: 16 },
  { name: "posuere metus", cardQuantity: 100, setId: 16 },
  { name: "turpis donec posuere metus", cardQuantity: 100, setId: 16 },
  { name: "parturient montes nascetur", cardQuantity: 100, setId: 16 },
  { name: "erat vestibulum sed", cardQuantity: 100, setId: 16 },
  { name: "cras in purus eu", cardQuantity: 100, setId: 17 },
  { name: "nibh in lectus", cardQuantity: 100, setId: 17 },
  { name: "dapibus at diam nam", cardQuantity: 100, setId: 17 },
  { name: "at dolor quis odio", cardQuantity: 100, setId: 17 },
  { name: "in imperdiet", cardQuantity: 100, setId: 17 },
  { name: "erat eros viverra eget", cardQuantity: 100, setId: 18 },
  { name: "libero nullam", cardQuantity: 100, setId: 18 },
  { name: "at ipsum ac tellus", cardQuantity: 100, setId: 18 },
  { name: "massa tempor convallis nulla", cardQuantity: 100, setId: 18 },
  { name: "vestibulum sagittis sapien", cardQuantity: 100, setId: 18 },
  { name: "ac leo pellentesque ultrices", cardQuantity: 100, setId: 19 },
  { name: "sit amet", cardQuantity: 100, setId: 19 },
  { name: "in hac", cardQuantity: 100, setId: 19 },
  { name: "ultricies eu", cardQuantity: 100, setId: 19 },
  { name: "habitasse platea dictumst maecenas", cardQuantity: 100, setId: 19 },
  { name: "sapien placerat ante", cardQuantity: 100, setId: 20 },
  { name: "nisl nunc nisl", cardQuantity: 100, setId: 20 },
  { name: "sit amet", cardQuantity: 100, setId: 20 },
  { name: "neque aenean", cardQuantity: 100, setId: 20 },
  { name: "nibh in", cardQuantity: 100, setId: 20 },
];

module.exports = subsets;
