const subsets = [
  {
    name: "tincidunt eu felis fusce",
    totalCards: 500,
    serializedTo: null,
    setId: 12,
  },
  {
    name: "interdum mauris ullamcorper purus",
    totalCards: 500,
    serializedTo: null,
    setId: 13,
  },
  {
    name: "morbi ut odio cras mi",
    totalCards: 200,
    serializedTo: null,
    setId: 22,
  },
  { name: "platea dictumst", totalCards: 500, serializedTo: null, setId: 22 },
  { name: "orci luctus et", totalCards: 300, serializedTo: null, setId: 3 },
  {
    name: "sodales scelerisque",
    totalCards: 300,
    serializedTo: null,
    setId: 11,
  },
  {
    name: "interdum eu tincidunt in leo",
    totalCards: 400,
    serializedTo: null,
    setId: 10,
  },
  { name: "tortor duis mattis", totalCards: 400, serializedTo: null, setId: 1 },
  {
    name: "consequat metus sapien",
    totalCards: 100,
    serializedTo: null,
    setId: 1,
  },
  {
    name: "ultricies eu nibh quisque id",
    totalCards: 500,
    serializedTo: null,
    setId: 15,
  },
  {
    name: "luctus et ultrices posuere cubilia",
    totalCards: 500,
    serializedTo: null,
    setId: 23,
  },
  {
    name: "quis lectus suspendisse potenti",
    totalCards: 300,
    serializedTo: null,
    setId: 22,
  },
  {
    name: "suscipit nulla elit ac nulla",
    totalCards: 300,
    serializedTo: null,
    setId: 11,
  },
  { name: "tincidunt ante vel", totalCards: 300, serializedTo: null, setId: 6 },
  { name: "morbi odio", totalCards: 100, serializedTo: null, setId: 17 },
  {
    name: "ut ultrices vel augue vestibulum",
    totalCards: 400,
    serializedTo: null,
    setId: 20,
  },
  {
    name: "ipsum praesent blandit lacinia erat",
    totalCards: 100,
    serializedTo: null,
    setId: 8,
  },
  {
    name: "scelerisque quam turpis adipiscing",
    totalCards: 100,
    serializedTo: null,
    setId: 22,
  },
  {
    name: "sit amet nunc viverra dapibus",
    totalCards: 400,
    serializedTo: null,
    setId: 1,
  },
  {
    name: "sed tristique in tempus sit",
    totalCards: 400,
    serializedTo: null,
    setId: 4,
  },
  { name: "primis in", totalCards: 400, serializedTo: null, setId: 13 },
  {
    name: "vestibulum sit amet",
    totalCards: 100,
    serializedTo: null,
    setId: 20,
  },
  {
    name: "mi in porttitor pede",
    totalCards: 100,
    serializedTo: null,
    setId: 2,
  },
  { name: "accumsan felis ut", totalCards: 300, serializedTo: null, setId: 12 },
  {
    name: "cursus id turpis integer",
    totalCards: 200,
    serializedTo: null,
    setId: 23,
  },
  { name: "vel dapibus", totalCards: 300, serializedTo: 320, setId: 25 },
  { name: "luctus et", totalCards: 500, serializedTo: null, setId: 11 },
  { name: "interdum eu", totalCards: 100, serializedTo: null, setId: 7 },
  {
    name: "odio justo sollicitudin ut suscipit",
    totalCards: 400,
    serializedTo: null,
    setId: 3,
  },
  { name: "molestie lorem", totalCards: 200, serializedTo: null, setId: 19 },
  {
    name: "nunc rhoncus dui vel sem",
    totalCards: 300,
    serializedTo: null,
    setId: 1,
  },
  {
    name: "sit amet lobortis sapien sapien",
    totalCards: 100,
    serializedTo: null,
    setId: 6,
  },
  {
    name: "sapien varius ut blandit",
    totalCards: 300,
    serializedTo: null,
    setId: 15,
  },
  { name: "fermentum donec ut", totalCards: 400, serializedTo: null, setId: 3 },
  { name: "ultrices posuere", totalCards: 200, serializedTo: null, setId: 24 },
  {
    name: "nisi nam ultrices libero",
    totalCards: 300,
    serializedTo: null,
    setId: 3,
  },
  {
    name: "tempor convallis nulla neque libero",
    totalCards: 400,
    serializedTo: null,
    setId: 12,
  },
  {
    name: "eget eleifend luctus ultricies",
    totalCards: 300,
    serializedTo: null,
    setId: 2,
  },
  { name: "mauris sit amet", totalCards: 100, serializedTo: null, setId: 11 },
  {
    name: "sit amet justo morbi ut",
    totalCards: 500,
    serializedTo: null,
    setId: 23,
  },
  {
    name: "ante vestibulum ante ipsum primis",
    totalCards: 300,
    serializedTo: null,
    setId: 11,
  },
  {
    name: "eu orci mauris lacinia",
    totalCards: 200,
    serializedTo: null,
    setId: 17,
  },
  { name: "nam dui proin leo", totalCards: 100, serializedTo: null, setId: 4 },
  { name: "in lacus", totalCards: 400, serializedTo: null, setId: 20 },
  {
    name: "nulla neque libero",
    totalCards: 400,
    serializedTo: null,
    setId: 24,
  },
  {
    name: "et ultrices posuere cubilia curae",
    totalCards: 200,
    serializedTo: null,
    setId: 9,
  },
  {
    name: "mi pede malesuada in",
    totalCards: 200,
    serializedTo: null,
    setId: 6,
  },
  {
    name: "lobortis ligula sit amet eleifend",
    totalCards: 200,
    serializedTo: null,
    setId: 10,
  },
  {
    name: "nisi volutpat eleifend donec ut",
    totalCards: 500,
    serializedTo: null,
    setId: 22,
  },
  {
    name: "tincidunt ante vel ipsum",
    totalCards: 200,
    serializedTo: 110,
    setId: 21,
  },
  {
    name: "quam nec dui luctus rutrum",
    totalCards: 100,
    serializedTo: null,
    setId: 3,
  },
  {
    name: "turpis enim blandit mi in",
    totalCards: 200,
    serializedTo: null,
    setId: 13,
  },
  { name: "ut odio cras mi", totalCards: 400, serializedTo: null, setId: 4 },
  {
    name: "viverra eget congue eget semper",
    totalCards: 100,
    serializedTo: null,
    setId: 12,
  },
  {
    name: "luctus tincidunt nulla mollis",
    totalCards: 100,
    serializedTo: null,
    setId: 12,
  },
  { name: "ut erat curabitur", totalCards: 500, serializedTo: null, setId: 19 },
  { name: "quis tortor id", totalCards: 200, serializedTo: null, setId: 7 },
  {
    name: "lectus in quam fringilla",
    totalCards: 400,
    serializedTo: 480,
    setId: 17,
  },
  {
    name: "vulputate luctus cum sociis",
    totalCards: 300,
    serializedTo: null,
    setId: 21,
  },
  {
    name: "luctus rutrum nulla",
    totalCards: 500,
    serializedTo: null,
    setId: 20,
  },
  { name: "libero convallis", totalCards: 200, serializedTo: 110, setId: 2 },
  { name: "primis in", totalCards: 100, serializedTo: null, setId: 8 },
  {
    name: "leo odio porttitor id consequat",
    totalCards: 100,
    serializedTo: null,
    setId: 1,
  },
  {
    name: "et ultrices posuere",
    totalCards: 100,
    serializedTo: 480,
    setId: 23,
  },
  {
    name: "nunc viverra dapibus",
    totalCards: 100,
    serializedTo: null,
    setId: 22,
  },
  {
    name: "lobortis est phasellus sit amet",
    totalCards: 300,
    serializedTo: 340,
    setId: 10,
  },
  { name: "sem praesent", totalCards: 200, serializedTo: null, setId: 9 },
  {
    name: "primis in faucibus",
    totalCards: 200,
    serializedTo: null,
    setId: 19,
  },
  {
    name: "nunc donec quis orci",
    totalCards: 400,
    serializedTo: null,
    setId: 3,
  },
  {
    name: "condimentum neque sapien placerat",
    totalCards: 100,
    serializedTo: null,
    setId: 22,
  },
  {
    name: "tristique est et tempus semper",
    totalCards: 100,
    serializedTo: null,
    setId: 10,
  },
  {
    name: "pellentesque eget nunc donec",
    totalCards: 300,
    serializedTo: null,
    setId: 17,
  },
  {
    name: "posuere cubilia curae duis",
    totalCards: 200,
    serializedTo: 160,
    setId: 4,
  },
  { name: "vel dapibus at", totalCards: 300, serializedTo: null, setId: 4 },
  { name: "diam in", totalCards: 100, serializedTo: null, setId: 2 },
  {
    name: "ultrices phasellus",
    totalCards: 200,
    serializedTo: null,
    setId: 25,
  },
  { name: "eu pede", totalCards: 300, serializedTo: null, setId: 4 },
  { name: "vitae mattis nibh", totalCards: 500, serializedTo: null, setId: 12 },
  {
    name: "diam id ornare imperdiet sapien",
    totalCards: 400,
    serializedTo: null,
    setId: 2,
  },
  { name: "dui vel sem", totalCards: 200, serializedTo: null, setId: 13 },
  { name: "accumsan tellus", totalCards: 400, serializedTo: null, setId: 25 },
  { name: "in purus", totalCards: 400, serializedTo: null, setId: 11 },
  { name: "nec molestie", totalCards: 300, serializedTo: null, setId: 10 },
  { name: "enim in", totalCards: 100, serializedTo: null, setId: 15 },
  {
    name: "nisl duis bibendum",
    totalCards: 200,
    serializedTo: null,
    setId: 10,
  },
  {
    name: "eget eleifend luctus",
    totalCards: 100,
    serializedTo: null,
    setId: 5,
  },
  { name: "non quam nec", totalCards: 100, serializedTo: null, setId: 7 },
  {
    name: "volutpat eleifend donec",
    totalCards: 500,
    serializedTo: null,
    setId: 13,
  },
  {
    name: "duis bibendum morbi non quam",
    totalCards: 400,
    serializedTo: null,
    setId: 22,
  },
  {
    name: "interdum venenatis turpis",
    totalCards: 500,
    serializedTo: 200,
    setId: 18,
  },
  {
    name: "turpis donec posuere metus",
    totalCards: 400,
    serializedTo: null,
    setId: 14,
  },
  {
    name: "nisl nunc rhoncus dui vel",
    totalCards: 500,
    serializedTo: null,
    setId: 9,
  },
  {
    name: "dui vel sem sed sagittis",
    totalCards: 300,
    serializedTo: null,
    setId: 22,
  },
  { name: "varius integer ac", totalCards: 300, serializedTo: null, setId: 18 },
  {
    name: "faucibus orci luctus et",
    totalCards: 200,
    serializedTo: null,
    setId: 20,
  },
  {
    name: "tellus in sagittis dui vel",
    totalCards: 100,
    serializedTo: null,
    setId: 25,
  },
  { name: "nibh quisque", totalCards: 200, serializedTo: null, setId: 24 },
  { name: "aliquam erat", totalCards: 100, serializedTo: null, setId: 12 },
  { name: "consequat morbi", totalCards: 500, serializedTo: 190, setId: 4 },
  { name: "mi pede malesuada", totalCards: 200, serializedTo: null, setId: 14 },
  { name: "in felis eu", totalCards: 200, serializedTo: null, setId: 24 },
  {
    name: "vestibulum velit id pretium",
    totalCards: 100,
    serializedTo: null,
    setId: 10,
  },
  { name: "ante ipsum", totalCards: 500, serializedTo: null, setId: 8 },
  { name: "maecenas pulvinar", totalCards: 400, serializedTo: null, setId: 17 },
  { name: "quam fringilla", totalCards: 200, serializedTo: null, setId: 6 },
  { name: "morbi quis", totalCards: 300, serializedTo: null, setId: 22 },
  {
    name: "potenti nullam porttitor lacus",
    totalCards: 300,
    serializedTo: 470,
    setId: 1,
  },
  { name: "in felis eu", totalCards: 100, serializedTo: null, setId: 9 },
  {
    name: "orci eget orci vehicula",
    totalCards: 200,
    serializedTo: null,
    setId: 20,
  },
  {
    name: "aliquet pulvinar sed nisl nunc",
    totalCards: 200,
    serializedTo: null,
    setId: 20,
  },
  { name: "et magnis", totalCards: 400, serializedTo: null, setId: 7 },
  {
    name: "ac lobortis vel dapibus at",
    totalCards: 500,
    serializedTo: null,
    setId: 2,
  },
  { name: "duis at", totalCards: 100, serializedTo: null, setId: 12 },
  {
    name: "ac leo pellentesque ultrices",
    totalCards: 400,
    serializedTo: null,
    setId: 4,
  },
  {
    name: "cubilia curae mauris",
    totalCards: 100,
    serializedTo: null,
    setId: 24,
  },
  {
    name: "semper porta volutpat",
    totalCards: 200,
    serializedTo: null,
    setId: 15,
  },
  { name: "donec vitae nisi", totalCards: 500, serializedTo: null, setId: 25 },
  {
    name: "rhoncus dui vel sem sed",
    totalCards: 100,
    serializedTo: null,
    setId: 13,
  },
  {
    name: "fusce posuere felis sed",
    totalCards: 200,
    serializedTo: null,
    setId: 20,
  },
  { name: "orci pede", totalCards: 400, serializedTo: null, setId: 6 },
  {
    name: "fusce consequat nulla",
    totalCards: 300,
    serializedTo: null,
    setId: 6,
  },
  {
    name: "pretium iaculis justo in",
    totalCards: 200,
    serializedTo: 180,
    setId: 21,
  },
  { name: "nulla facilisi", totalCards: 200, serializedTo: null, setId: 6 },
  { name: "ipsum primis", totalCards: 200, serializedTo: 260, setId: 1 },
  { name: "est phasellus", totalCards: 500, serializedTo: null, setId: 10 },
  {
    name: "nec condimentum neque sapien placerat",
    totalCards: 500,
    serializedTo: null,
    setId: 9,
  },
  { name: "eleifend donec", totalCards: 500, serializedTo: 490, setId: 18 },
  { name: "magna at nunc", totalCards: 200, serializedTo: null, setId: 17 },
  {
    name: "at vulputate vitae",
    totalCards: 300,
    serializedTo: null,
    setId: 10,
  },
  {
    name: "phasellus id sapien in sapien",
    totalCards: 400,
    serializedTo: null,
    setId: 23,
  },
  { name: "quam nec dui luctus", totalCards: 200, serializedTo: 120, setId: 8 },
  {
    name: "orci luctus et ultrices posuere",
    totalCards: 500,
    serializedTo: null,
    setId: 7,
  },
  {
    name: "consectetuer adipiscing elit",
    totalCards: 500,
    serializedTo: null,
    setId: 5,
  },
  { name: "proin leo", totalCards: 400, serializedTo: null, setId: 14 },
  { name: "velit id", totalCards: 100, serializedTo: null, setId: 11 },
  {
    name: "accumsan tortor quis turpis",
    totalCards: 100,
    serializedTo: null,
    setId: 21,
  },
  {
    name: "justo nec condimentum",
    totalCards: 500,
    serializedTo: null,
    setId: 19,
  },
  {
    name: "pellentesque ultrices",
    totalCards: 100,
    serializedTo: null,
    setId: 4,
  },
  {
    name: "in felis eu sapien cursus",
    totalCards: 100,
    serializedTo: null,
    setId: 17,
  },
  {
    name: "lectus aliquam sit amet diam",
    totalCards: 100,
    serializedTo: null,
    setId: 18,
  },
  {
    name: "nam congue risus semper porta",
    totalCards: 400,
    serializedTo: 380,
    setId: 16,
  },
  {
    name: "venenatis non sodales sed",
    totalCards: 200,
    serializedTo: null,
    setId: 3,
  },
  {
    name: "condimentum curabitur in libero",
    totalCards: 500,
    serializedTo: null,
    setId: 22,
  },
  {
    name: "quam turpis adipiscing",
    totalCards: 300,
    serializedTo: null,
    setId: 11,
  },
  { name: "nulla elit", totalCards: 500, serializedTo: null, setId: 25 },
  { name: "pellentesque eget", totalCards: 400, serializedTo: 440, setId: 4 },
  { name: "ac enim", totalCards: 100, serializedTo: null, setId: 20 },
  { name: "sagittis nam", totalCards: 300, serializedTo: null, setId: 13 },
  { name: "mi pede", totalCards: 100, serializedTo: null, setId: 17 },
  {
    name: "amet sapien dignissim vestibulum vestibulum",
    totalCards: 100,
    serializedTo: 380,
    setId: 10,
  },
  {
    name: "pulvinar nulla pede ullamcorper augue",
    totalCards: 100,
    serializedTo: null,
    setId: 7,
  },
  {
    name: "in porttitor pede justo",
    totalCards: 500,
    serializedTo: null,
    setId: 23,
  },
  {
    name: "donec posuere metus vitae",
    totalCards: 500,
    serializedTo: null,
    setId: 22,
  },
  { name: "nunc purus", totalCards: 300, serializedTo: null, setId: 10 },
  {
    name: "blandit lacinia erat vestibulum sed",
    totalCards: 200,
    serializedTo: null,
    setId: 21,
  },
  {
    name: "pulvinar nulla pede ullamcorper augue",
    totalCards: 500,
    serializedTo: 20,
    setId: 14,
  },
  {
    name: "dictumst maecenas ut",
    totalCards: 200,
    serializedTo: null,
    setId: 7,
  },
  {
    name: "augue vestibulum rutrum",
    totalCards: 200,
    serializedTo: null,
    setId: 10,
  },
  {
    name: "lectus in quam fringilla",
    totalCards: 500,
    serializedTo: null,
    setId: 7,
  },
  { name: "at ipsum", totalCards: 400, serializedTo: null, setId: 10 },
  {
    name: "maecenas leo odio condimentum",
    totalCards: 500,
    serializedTo: null,
    setId: 22,
  },
  {
    name: "scelerisque mauris",
    totalCards: 200,
    serializedTo: null,
    setId: 10,
  },
  {
    name: "turpis nec euismod",
    totalCards: 100,
    serializedTo: null,
    setId: 11,
  },
  {
    name: "risus semper porta",
    totalCards: 200,
    serializedTo: null,
    setId: 21,
  },
  { name: "at nunc", totalCards: 200, serializedTo: null, setId: 4 },
  {
    name: "vestibulum ante ipsum",
    totalCards: 500,
    serializedTo: null,
    setId: 20,
  },
  {
    name: "purus phasellus in felis",
    totalCards: 400,
    serializedTo: null,
    setId: 5,
  },
  {
    name: "aliquam convallis nunc proin",
    totalCards: 500,
    serializedTo: null,
    setId: 25,
  },
  { name: "pretium iaculis", totalCards: 200, serializedTo: null, setId: 25 },
  {
    name: "diam cras pellentesque volutpat",
    totalCards: 500,
    serializedTo: 320,
    setId: 6,
  },
  {
    name: "sed augue aliquam erat",
    totalCards: 500,
    serializedTo: null,
    setId: 16,
  },
  {
    name: "iaculis congue vivamus metus",
    totalCards: 400,
    serializedTo: null,
    setId: 2,
  },
  {
    name: "sapien dignissim vestibulum vestibulum",
    totalCards: 100,
    serializedTo: null,
    setId: 22,
  },
  {
    name: "sit amet consectetuer adipiscing elit",
    totalCards: 500,
    serializedTo: null,
    setId: 22,
  },
  { name: "sem sed sagittis", totalCards: 100, serializedTo: null, setId: 2 },
  {
    name: "amet eleifend pede libero",
    totalCards: 300,
    serializedTo: null,
    setId: 25,
  },
  { name: "porta volutpat", totalCards: 200, serializedTo: 230, setId: 7 },
  {
    name: "lectus pellentesque eget",
    totalCards: 200,
    serializedTo: 320,
    setId: 4,
  },
  { name: "quis turpis", totalCards: 100, serializedTo: null, setId: 7 },
  {
    name: "erat curabitur gravida",
    totalCards: 500,
    serializedTo: null,
    setId: 2,
  },
  { name: "sollicitudin ut", totalCards: 200, serializedTo: null, setId: 3 },
  { name: "pede lobortis", totalCards: 400, serializedTo: null, setId: 14 },
  { name: "proin leo", totalCards: 100, serializedTo: null, setId: 11 },
  {
    name: "in lectus pellentesque at nulla",
    totalCards: 100,
    serializedTo: null,
    setId: 20,
  },
  {
    name: "curae nulla dapibus",
    totalCards: 100,
    serializedTo: 170,
    setId: 24,
  },
  { name: "a pede", totalCards: 200, serializedTo: null, setId: 19 },
  { name: "felis fusce", totalCards: 300, serializedTo: null, setId: 8 },
  {
    name: "turpis sed ante vivamus",
    totalCards: 400,
    serializedTo: null,
    setId: 21,
  },
  {
    name: "massa volutpat convallis morbi",
    totalCards: 500,
    serializedTo: null,
    setId: 24,
  },
  { name: "lorem ipsum dolor", totalCards: 500, serializedTo: 70, setId: 24 },
  {
    name: "gravida sem praesent",
    totalCards: 200,
    serializedTo: null,
    setId: 18,
  },
  {
    name: "vestibulum rutrum rutrum neque",
    totalCards: 300,
    serializedTo: null,
    setId: 12,
  },
  { name: "primis in", totalCards: 100, serializedTo: null, setId: 4 },
  {
    name: "dictumst aliquam augue quam sollicitudin",
    totalCards: 300,
    serializedTo: null,
    setId: 7,
  },
  {
    name: "diam erat fermentum",
    totalCards: 200,
    serializedTo: null,
    setId: 6,
  },
  {
    name: "dui maecenas tristique",
    totalCards: 200,
    serializedTo: null,
    setId: 7,
  },
  {
    name: "pellentesque volutpat dui maecenas",
    totalCards: 100,
    serializedTo: null,
    setId: 15,
  },
  {
    name: "nec molestie sed justo pellentesque",
    totalCards: 300,
    serializedTo: null,
    setId: 10,
  },
  {
    name: "aenean sit amet justo",
    totalCards: 200,
    serializedTo: 420,
    setId: 2,
  },
  {
    name: "neque vestibulum eget",
    totalCards: 200,
    serializedTo: null,
    setId: 2,
  },
];

module.exports = subsets;
